# CPE15 MIDTERM PROJECT - Cleaning Notebook
---
## Part I: Field Data Collection, Validation, Cleaning, and Documentation
---
### BSCPE 3GF
### Submitted on: Oct 11, 2026

In [58]:
import numpy as np
import pandas as pd

## Function Definitions

In [59]:
columns = [
      'feature_id', 'name', 'category', 'subcategory',
      'street', 'barangay', 'Latitude', 'Longitude',
      'location_description', 'operating_status', 'opening_hours',
      'contact_info', 'collector', 'date_collected',
      'remarks', 'verified'
  ]

def read_csv_files(x):

  df = pd.read_csv(x, usecols = columns)
  df = df[columns]

  return df

In [60]:
def clean_mixed_dates(df):

    df['date_collected'] = (
        df['date_collected']
        .astype('string')
        .str.strip()
        .str.replace('_', '-', regex=False)
    )

    df['date_collected'] = pd.to_datetime(
        df['date_collected'],
        format='mixed',
        dayfirst=True,
        errors='coerce'
    )

    return df

## Importing the raw datas (csv files from Google Drive)

In [61]:
# uc?export=download&id=

"""raw_datasets = { # raw datasets and their respective Google Drive URL links dictionary
    'raw_dataset_1': 'https://drive.google.com/uc?export=download&id=162Obps98STe5tsq5bFEl3gAzDPxfqblR',
    'raw_dataset_2': 'https://drive.google.com/uc?export=download&id=1QLZKJY8HiF-IQvFVZbpia9qA2yroEmoS',
    'raw_dataset_3': 'https://drive.google.com/uc?export=download&id=1RXOvapKILTYGc1biL42rjFjlB-I5t9JM',
    'raw_dataset_4': 'https://drive.google.com/uc?export=download&id=1Kze7v7q5nCR0nWUjlPjsjTKUtvWGibDL',
    'raw_dataset_5': 'https://drive.google.com/uc?export=download&id=196zcPBcRJIJgNMhmgRsrgJLwpC5gEZD5',
    'raw_dataset_6': 'https://drive.google.com/uc?export=download&id=1o0KullNbJ5t0cE_fm3QFSagFLfIFmrpC',
    'raw_dataset_7': 'https://drive.google.com/uc?export=download&id=1lTc9XVU5lgTNG0dGgKnnGnw3TGQJjq0S',
    'raw_dataset_8': 'https://drive.google.com/uc?export=download&id=1Celn9JNcsmKjmjjsxSo9BwW0BxSzspn1',
    'raw_dataset_9': 'https://drive.google.com/uc?export=download&id=1-_jGqHAioiHgjfKxUuWmuyV2ebja9Qoc',
    'raw_dataset_10': 'https://drive.google.com/uc?export=download&id=1KEqPvlOY4M43ptcfC2Qmg5CKpDb9ravw'
}"""

raw_datasets = { # raw datasets and their respective Google Drive URL links dictionary
    'raw_dataset_1': 'raw_dataset_1.csv',
    'raw_dataset_2': 'raw_dataset_2.csv',
    'raw_dataset_3': 'raw_dataset_3.csv',
    'raw_dataset_4': 'raw_dataset_4.csv',
    'raw_dataset_5': 'raw_dataset_5.csv',
    'raw_dataset_6': 'raw_dataset_6.csv',
    'raw_dataset_7': 'raw_dataset_7.csv',
    'raw_dataset_8': 'raw_dataset_8.csv',
    'raw_dataset_9': 'raw_dataset_9.csv',
    'raw_dataset_10': 'raw_dataset_10.csv'
}



processed_datasets = {}

for name, url in raw_datasets.items():
    df = read_csv_files(url)
    df = clean_mixed_dates(df)
    df['source'] = name
    processed_datasets[name] = df

### Checking individual datasets

In [62]:
df1 = processed_datasets['raw_dataset_1']
df1.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B10_001,"mommy's tacos, burgers and pizzas",Food and Dining,Eatery,G.Cadeliña,Barangay 10,14.112738,121.557460,food stall at the front with an eatery inside,open,9:00AM - 8:00pm,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
1,LUC_B10_002,bnb laundry,Personal Services,Laundry,G.Cadeliña,Barangay 10,14.112738,121.557460,"Next to mommy's tacos, burgers and pizzas",open,7:00AM - 7:00pm,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
2,LUC_B10_003,Star commecial,Retail,Grocery,G.Cadeliña,Barangay 10,14.112720,121.557561,"face to face of mommy's tacos, burger and pizzas",open,7:00AM - 7:00pm,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
3,LUC_B10_004,ICE ICE BABY,Other,Other,G.Cadeliña,Barangay 10,14.112880,121.557524,front have a gate colored brown,open,9:00AM-9:00PM,NaN,"BROQUEZA, MIKYLA C.",NaT,NaN,Yes,raw_dataset_1
4,LUC_B10_005,Zendong,Food and Dining,Eatery,G.Cadeliña,Barangay 10,14.112940,121.557613,grey metal gate,open,NaN,NaN,"BROQUEZA, MIKYLA C.",NaT,NaN,Yes,raw_dataset_1

In [63]:
df2 = processed_datasets['raw_dataset_2']
df2.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B02_025,Ven's Puto Seko,Food and Dining,Souvenir,A. Bonifacio,Barangay 2,14.113378,121.555077,NaN,Closed,NaN,NaN,"ALFARO, Justin Alexandre, B",2026-09-29,NaN,Yes,raw_dataset_2
1,LUC_B02_026,"Bumibili Ginto at Pilak Sirang Alahas, Old coins",Financial,Pawnshop,A. Bonifacio,Barangay 2,14.113487,121.554902,NaN,Closed,NaN,NaN,"MACARAIG, Mark Rheniel, P",2026-09-29,NaN,Yes,raw_dataset_2
2,LUC_B02_027,Kimpoy Shoes Bags Repair,Automotive,Repair Shop,A. Bonifacio,Barangay 2,14.113875,121.554072,NaN,Closed,NaN,9.602081e+09,"PALMA, Mark, M.",2026-09-29,NaN,Yes,raw_dataset_2
3,LUC_B02_028,Nicolo's Milk Tea,Food and Dining,Cafe,A. Bonifacio,Barangay 2,14.113868,121.553998,NaN,Closed,NaN,NaN,"HUTAMARES, Franchezka, S.",2026-09-29,NaN,Yes,raw_dataset_2
4,LUC_B02_029,Frosty Hail - Purified Tube Ice,Retail,Other,A. Bonifacio,Barangay 2,14.113858,121.553960,NaN,Closed,NaN,9.310402e+09,"RAMOS, Isaih Thomas, E.",2026-09-29,NaN,Yes,raw_dataset_2

In [64]:
df3 = processed_datasets['raw_dataset_3']
df3.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B09_001,Agee's Food Hub,Food and Dining,Restaurant,La Purisima Conception,Barangay 9,14.114794,121.555984,First floor,Open,NaN,NaN,"Salumbides, Emanuel A.",2026-10-02,NaN,Yes,raw_dataset_3
1,LUC_B09_002,The Lemon LAB PH,Food and Dining,Restaurant,Don V. Cadelina,Barangay 9,14.114910,121.556125,NaN,Open,NaN,NaN,"Escobal, Gwyneth A.",2026-10-02,NaN,Yes,raw_dataset_3
2,LUC_B09_003,LHCN Fashion Botique,Retail,Clothing,Don V. Cadelina,Barangay 9,14.115035,121.556058,First floor,Open,NaN,NaN,"Reginal,Reynel M.",2026-10-02,NaN,Yes,raw_dataset_3
3,LUC_B09_004,Ropharisa Photo Image,Professional Services,Printing Shop,Regidor,Barangay 9,14.115123,121.555711,Second floor,Open,NaN,9399079761,"Salumbides, Emanuel A",2026-10-02,NaN,Yes,raw_dataset_3
4,LUC_B09_005,Dahilig Live Tilapia,Other,Other,Regidor,Barangay 9,14.115154,121.555698,first floor,closed,NaN,540-4079,"Escobal, Gwyneth A.",2026-10-02,NaN,Yes,raw_dataset_3

In [65]:
df4 = processed_datasets['raw_dataset_4']
df4.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B08_011,Abcede's Resto,Food and Dining,Restaurant,Quezon Avenue,Barangay 8,14.113632,121.556235,NaN,Open,NaN,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4
1,LUC_B08_012,Generica drugstore,Health,Pharmacy,Quezon Avenue,Barangay 8,14.113742,121.556199,NaN,Open,7:00am to 9:00pm,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4
2,LUC_B08_013,Lola Pelang's,Food and Dining,Eatery,Quezon Avenue,Barangay 8,14.113745,121.556150,NaN,Open,NaN,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4
3,LUC_B08_014,Dadbod,Food and Dining,Restaurant,Quezon Avenue,Barangay 8,14.113823,121.555927,NaN,Closed,NaN,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4
4,LUC_B08_016,Mang Inasal,Food and Dining,Fast Food,Quezon Avenue,Barangay 8,14.113894,121.555589,NaN,Open,NaN,NaN,"Alfaro, Justin Alexandre, B.",2026-10-01,NaN,Yes,raw_dataset_4

In [66]:
df5 = processed_datasets['raw_dataset_5']
df5.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_BO5_001,Lote Fitness Gym,Food and Dining,Restaurant,Fidel Rada St.,Barangay 5,14.112805,121.555890,Near Multi Purpose hall,Open,8:00am,NaN,Mark Gabriel E. Susim,2026-03-10,Near Multi purpose hall,Yes,raw_dataset_5
1,LUC_B05_002,Brgy. 5 Multi-Purpose Hall,Government,Barangay Office,Balintawak St.,Barangay 1,14.112387,121.555653,Dulo ng balintawak street,Open,8:00am - 5:00pm,NaN,Mark Gabriel E. Susin,2026-10-03,NaN,Yes,raw_dataset_5
2,LUC_B05_003,Pedron Dental Clinic,Health,Dental Clinic,NaN,Barangay 1,14.112435,121.555725,near brgy 5 multi-purpose hall,open,Monday-Saturday: 9:00 AM - 6 PM,FB: PedronDentalClinic,"Dela Cruz, Shane Theresse A.",2026-10-03,NaN,Yes,raw_dataset_5
3,LUC_B05_004,SK Hall,Government,Barangay Office,Balintawak St.,Barangay 1,14.112577,121.555748,near brgy. hall,close,NaN,NaN,"Liwanag, Micaela A.",2026-10-03,NaN,Yes,raw_dataset_5
4,LUC_B05_005,Mikay Sari-Sari Store,Food and Dining,Restaurant,Balintawak st.,Barangay 1,14.112661,121.555883,Near Lote fitness gym and Multi-purpose hall,open,7:00am to 8:00pm,NaN,Mark Gabriel E. Susim,2026-10-03,NaN,Yes,raw_dataset_5

In [67]:
df6 = processed_datasets['raw_dataset_6']
df6.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B04_001,ZUREA Hotel,Accommodation,Hotel,Conception,Barangay 4,14.116247,121.552579,NaN,Open,NaN,NaN,"ARELLANO, Arvin, L.",2026-09-29,NaN,Yes,raw_dataset_6
1,LUC_B04_002,NaN,Retail,Other,Conception,Barangay 4,14.116294,121.552381,NaN,open,5:30am - 8:00pm,9393211820,"ARELLANO, Arvin, L.",2026-09-29,NaN,Yes,raw_dataset_6
2,LUC_B04_003,NaN,Retail,Sari Sari Store,Conception,Barangay 4,14.116414,121.552138,NaN,Open,NaN,NaN,"ERINCO, Raphael Joshua, V.",2026-09-29,NaN,Yes,raw_dataset_6
3,LUC_B04_004,NaN,Personal Services,Barbershop,Conception,Barangay 4,14.116446,121.552053,NaN,Open,NaN,NaN,"ERINCO, Raphael Joshua V.",2026-09-29,NaN,Yes,raw_dataset_6
4,LUC_B04_005,Irene's Sewing Shop,Personal Services,Other,Conception,Barangay 4,14.116468,121.552010,Near barbershop,open,NaN,NaN,"ERINCO, Raphael Joshua V.",2026-09-29,NaN,Yes,raw_dataset_6

In [68]:
df7 = processed_datasets['raw_dataset_7']
df7.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B02_001,NaN,Accommodation,Boarding House,A. Racelis,Barangay 2,14.112478,121.557781,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,raw_dataset_7
1,LUC_B02_002,Abustan Funeral Parlor,Professional Services,Office,A. Bonifacio,Barangay 2,14.112460,121.557451,Along Kamatian River,Closed,NaN,9424529778,"PALMA, Mark M.",2026-09-28,NaN,Yes,raw_dataset_7
2,LUC_B02_003,Lhoida Sari Sari Store,Retail,Sari Sari Store,G. Cadeliña,Barangay 2,14.112406,121.557380,Alongside Abustan Funeral Parlor,Open,7:00 AM - 8:00 PM,NaN,"RAMOS, Isaih Thomas E.",2026-09-28,NaN,Yes,raw_dataset_7
3,LUC_B02_004,Tan-Tan,Automotive,Repair Shop,A. Bonifacio,Barangay 2,14.112446,121.557227,NaN,Closed,NaN,9289986453,"ARELLANO, Arvin L.",2026-09-28,NaN,Yes,raw_dataset_7
4,LUC_B02_005,VMCO Sari Sari Store,Retail,Sari Sari Store,A. Bonifacio,Barangay 2,14.112599,121.556882,NaN,Open,6:00 AM - 11:00 PM,NaN,"QUEBRADO, Lance Wayne Y.",2026-09-28,NaN,Yes,raw_dataset_7

In [69]:
df8 = processed_datasets['raw_dataset_8']
df8.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B02_019,Balmeo's Special Longganisang Lucban,Retail,Other,A. Bonifacio Street,Barangay 2,14.113583,121.554619,NaN,Open,NaN,9228542179,"ARELLANO, Arvin, L.",2026-09-28,NaN,Yes,raw_dataset_8
1,LUC_B02_020,Shower Of Blessing,Retail,Grocery,NaN,Barangay 2,14.113766,121.554399,NaN,Closed,NaN,(042) 540-6181,"ARELLANO, Arvin, L.",2026-09-28,NaN,Yes,raw_dataset_8
2,LUC_B02_021,CARD MBA,Financial,Bank,A. Bonifacio,Barangay 2,14.113655,121.554366,NaN,Closed,NaN,NaN,"GONZALES, Louis,",2026-09-28,NaN,Yes,raw_dataset_8
3,LUC_B02_022,Mervin and Vivian Motor Parts And Repair,Automotive,Repair Shop,A. Bonifacio,Barangay 2,14.113735,121.554304,NaN,Closed,NaN,9383858601,"PALMA, Mark, M.",2026-09-28,NaN,Yes,raw_dataset_8
4,LUC_B02_023,Jun Balmeo Store,Retail,Grocery,A. Bonifacio,Barangay 2,14.113774,121.554104,NaN,Closed,NaN,NaN,"RAMOS, Isaih Thomas, E.",2026-09-28,Long standing grocery for sari sari store,Yes,raw_dataset_8

In [70]:
df9 = processed_datasets['raw_dataset_9']
df9.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B03_001,Hazzie Store,Retail,Sari-sari Store,Hobart Dator Street,Barangay 3,14.114486,121.550593,NaN,Open,6:00 am - 7:00 pm,NaN,"ANGULO, Leira Rose A.",2026-03-10,NaN,Yes,raw_dataset_9
1,LUC_B03_002,Ning's Store,Retail,Sari-sari Store,Hobart Dator Street,Barangay 3,14.114090,121.550055,NaN,Open,6:00 am - 6:00 pm,NaN,"DE LEON, Trisha Sandra P.",2026-03-10,NaN,Yes,raw_dataset_9
2,LUC_B03_003,Cabigan Mini Store,Retail,Sari-sari Store,Hobart Dator Street,Barangay 3,14.114840,121.551049,NaN,Open,6:00 am - 11:00 pm,NaN,"DIOSAY, Angelica A.",2026-03-10,NaN,Yes,raw_dataset_9
3,LUC_B03_004,VM Sun,Retail,Clothing,A. Bonifacio,Barangay 3,14.115182,121.551094,NaN,Open,NaN,NaN,"FONTANILLA, Christian Jay N.",2026-03-10,NaN,Yes,raw_dataset_9
4,LUC_B03_005,EKRM Store,Retail,Convenience Store,129 Cadavez St.,Barangay 3,14.115302,121.550800,NaN,Open,5:00 am - 10:00 pm,0949-719-2228,"MERCADO, Mhaylan Say R.",2026-03-10,NaN,Yes,raw_dataset_9

In [71]:
df10 = processed_datasets['raw_dataset_10']
df10.head()

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B06_001,RMT's Clinical Laboratory,Health,Clinic,Placencia Street,Barangay 6,14.115498,121.554032,corner of the street. connected to RRN Interac...,open,NaN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10
1,LUC_B06_002,RRN Integrative Health Clinic,Health,Clinic,Placencia Street,Barangay 6,14.115498,121.554032,Corner of the street. Connected to RMT's Clini...,open,9:00AM-12:00NN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10
2,LUC_B06_003,The Skin Health Clinic,Health,Clinic,Placencia Street,Barangay 6,14.115498,121.554032,Corner of the street. Connected with RMT's Cli...,open,9:30AM-1:00PM,NaN,"Libao, Ried Carlo C.",2026-05-10,Dermatology Clinic,Yes,raw_dataset_10
3,LUC_B06_004,Parinas Medical Clinic,Health,Clinic,Placencia Street,Barangay 6,14.115498,121.554032,Corner of the street. Connected to RRN Integra...,open,NaN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10
4,LUC_B06_005,CE MARTINEZ APPAREL SHOP,Professional Sevices,Sewing Shop,La Purisima Concepcion,Barangay 6,14.115530,121.553960,NaN,open,NaN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10

## Setting up the dataframe

In [72]:
# Data Aggregation

df_raw = pd.concat(processed_datasets.values(), ignore_index=True)
df = df_raw.copy()

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   feature_id            767 non-null    str
 1   name                  744 non-null    str
 2   category              767 non-null    str
 3   subcategory           767 non-null    str
 4   street                758 non-null    str
 5   barangay              767 non-null    str
 6   Latitude              767 non-null    float64
 7   Longitude             767 non-null    float64
 8   location_description  99 non-null     object
 9   operating_status      762 non-null    str
 10  opening_hours         127 non-null    str
 11  contact_info          142 non-null    object
 12  collector             765 non-null    str
 13  date_collected        753 non-null    datetime64[us]
 14  remarks               61 non-null     object
 15  verified              767 non-null    str
 16  source                767 non-null    str
dtypes: datetime64[us](1), float64(2), object(3), str(11)
memory usage: 102.0+ KB

In [74]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nUnique feature IDs:")
print(df['feature_id'].nunique())

print("\nDuplicate feature IDs:")
print(df['feature_id'].duplicated().sum())

Rows: 767
Columns: 17

Missing values:
feature_id                0
name                     23
category                  0
subcategory               0
street                    9
barangay                  0
Latitude                  0
Longitude                 0
location_description    668
operating_status          5
opening_hours           640
contact_info            625
collector                 2
date_collected           14
remarks                 706
verified                  0
source                    0
dtype: int64

Duplicate rows:
1

Unique feature IDs:
705

Duplicate feature IDs:
62

In [75]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Latitude,767.0,14.114736,14.112305,14.113661,14.114564,14.115615,14.11882,0.001388
Longitude,767.0,121.554817,121.550036,121.553281,121.554996,121.556311,121.558577,0.001875
date_collected,753,2026-11-05 09:45:10.756972,2026-01-10 00:00:00,2026-05-10 00:00:00,2026-10-01 00:00:00,2026-10-01 00:00:00,2206-10-03 00:00:00,NaN

In [76]:
df['feature_id'].value_counts()

feature_id
LUC_B04_026    6
LUC_B04_003    3
LUC_B04_009    3
LUC_B04_012    3
LUC_B04_016    3
              ..
LUC_B06_064    1
LUC_B06_065    1
LUC_B06_066    1
LUC_B06_067    1
LUC_B06_068    1
Name: count, Length: 705, dtype: int64

In [77]:
print("feature_id:", df['feature_id'].nunique(), "\ntotal entries:", len(df))

feature_id: 705
total entries: 767

In [78]:
df['name'].value_counts()

name
Lucky Bookstore                 3
Ven's Puto Seko                 3
Colar                           3
Boss Tabi Inihaw                2
Shiela's Frozen Product         2
                               ..
Roland's Lambanog               1
Petshop                         1
BiggieTalk Global Department    1
Myori's                         1
Deveza Farm                     1
Name: count, Length: 722, dtype: int64

In [79]:
df['barangay'].value_counts()

barangay
Barangay 8     162
Barangay 9     126
Barangay 2     114
Barangay 10    103
Barangay 4     102
Barangay 6      68
Barangay 5      32
Barangay 1      30
Barangay 3      30
Name: count, dtype: int64

In [80]:
df['collector'].value_counts().head(15)

collector
ERINCO, Raphael Joshua V.           55
ARELLANO, Arvin L.                  48
Cadao, Janusz Gabriel S.            39
APOSTOL, Janelle Mae A.             38
Escobal, Gwyneth A.                 34
Reginal, Reynel M.                  31
Salumbides, Emanuel A.              29
Libao, Ried Carlo C.                29
PALMA, Mark, M.                     24
Javin, Mark Justine P.              22
ABRACIA, JESHEILA ANGELA J.         21
RAMOS, Isaih Thomas, E.             21
De Chavez, Sharaine Princess, P.    21
Alfaro, Justin Alexandre, B.        21
Carable, Jillian Mae, V.            19
Name: count, dtype: int64

In [81]:
df['category'].value_counts()

category
Retail                   288
Food and Dining          187
Personal Services         65
Other                     49
Professional Services     43
Health                    43
Financial                 30
Accommodation             18
Automotive                15
Government                11
Professional Sevices       9
Tourism                    8
Financial Services         1
Name: count, dtype: int64

In [82]:
df['category'].value_counts()

category
Retail                   288
Food and Dining          187
Personal Services         65
Other                     49
Professional Services     43
Health                    43
Financial                 30
Accommodation             18
Automotive                15
Government                11
Professional Sevices       9
Tourism                    8
Financial Services         1
Name: count, dtype: int64

In [83]:
df['subcategory'].value_counts()

subcategory
Other                 134
Sari Sari Store       112
Eatery                 56
Restaurant             44
Grocery                37
                     ...
CDC                     1
Transport Station       1
Pet Shop                1
Teaching Services       1
Tourist Attraction      1
Name: count, Length: 61, dtype: int64

In [84]:
df['operating_status'].value_counts()

operating_status
Open                  448
open                  202
Closed                 56
CLOSED                 36
closed                  6
close                   4
OPEN                    4
Close                   2
closed on Saturday      1
Oepn                    1
closel                  1
8AM - 2AM               1
Name: count, dtype: int64

In [85]:
df['street'].value_counts().head(20)

street
Quezon Avenue             101
A. Racelis                 64
San Luis                   53
Lucban-Sampaloc Road       37
A. Bonifacio               32
La Purisima Concepcion     30
Katipunan                  28
Regidor                    27
Fidel Rada                 21
Don V. Cadelina            17
Gomburza Street            17
General Lukban Street      14
Bonifacio                  14
Gomburza                   13
Gen. Lukban                12
Quezon avenue              11
La Purisma Concepcion      11
Rizal Avenue               11
Lopez Jaena                10
Racelis                    10
Name: count, dtype: int64

In [86]:
df['verified'].value_counts()

verified
Yes    767
Name: count, dtype: int64

In [87]:
df["Latitude"].value_counts().head(10)

Latitude
14.115498    4
14.112825    3
14.112738    2
14.113257    2
14.113625    2
14.113183    2
14.113382    2
14.114518    2
14.115578    2
14.116286    2
Name: count, dtype: int64

In [88]:
df['Longitude'].value_counts().head(10)

Longitude
121.554032    4
121.557915    3
121.557460    2
121.557573    2
121.557527    2
121.557200    2
121.553960    2
121.553248    2
121.555804    2
121.556022    2
Name: count, dtype: int64

In [89]:
df[['Latitude', 'Longitude']].duplicated().value_counts()

False    756
True      11
Name: count, dtype: int64

In [90]:
df[df['barangay'] == 'Barangay 1']

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
103,LUC_B01_002,Osolle Electrical Supply,Retail,Electronics,La Purisma Concepcion,Barangay 1,14.114010,121.557813,NaN,open,NaN,09605149058,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
104,LUC_B01_003,Rkov Motorcle Parts,Automotive,Parts Shop,La Purisma Concepcion,Barangay 1,14.114160,121.557410,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
105,LUC_B01_004,Yssa's Sari-sari Store,Retail,Sari Sari Store,La Purisma Concepcion,Barangay 1,14.114218,121.557288,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
106,LUC_B01_005,Purr J,Retail,Other,La Purisma Concepcion,Barangay 1,14.114335,121.557112,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
107,LUC_B01_006,Flora's Sari-sari Store,Retail,Sari Sari Store,La Purisma Concepcion,Barangay 1,14.114242,121.557008,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
108,LUC_B01_007,Kabasi's Sari-sari Store,Retail,Sari Sari Store,La Purisma Concepcion,Barangay 1,14.114413,121.556889,NaN,closed,6:00 AM - 10:00 PM,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
109,LUC_B01_008,Rosemarie Store,Retail,Sari Sari Store,La Purisma Concepcion,Barangay 1,14.114548,121.556533,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
110,LUC_B01_009,Good Shepherd Diocesan School-IFI,Other,Other,La Purisma Concepcion,Barangay 1,14.114551,121.556408,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
111,LUC_B01_010,Kenby Pet Supplies,Retail,Other,La Purisma Concepcion,Barangay 1,14.114697,121.556160,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
112,LUC_B01_011,Chicks and Babes,Food and Dining,Restaurant,La Purisma Concepcion,Barangay 1,14.114675,121.556067,NaN,open,NaN,09088978077,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
113,LUC_B01_012,Agee's Food Hub,Food and Dining,Eatery,La Purisma Concepcion,Barangay 1,14.114733,121.555983,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
114,LUC_B01_013,The Lemon Hub Ph,Food and Dining,Other,Don V. Cadelina,Barangay 1,14.114925,121.556148,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
115,LUC_B01_014,FE Store,Retail,Sari Sari Store,Don V. Cadelina,Barangay 1,14.115010,121.556068,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
116,LUC_B01_015,Aldartek Engineering Services,Professional Services,Electronics,Lopez Jaena,Barangay 1,14.114952,121.556375,NaN,open,NaN,09228404233,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
117,LUC_B01_016,V.L. Avila Variety Store,Retail,Sari Sari Store,Lopez Jaena,Barangay 1,14.114858,121.556507,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
118,LUC_B01_017,PH Resto,Food and Dining,Restaurant,Lopez Jaena,Barangay 1,14.114628,121.557077,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
284,LUC-B08_036,SJS,Retail,Other,Quezon Avenue,Barangay 1,14.114383,121.554680,NaN,Open,NaN,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4
335,LUC_B05_002,Brgy. 5 Multi-Purpose Hall,Government,Barangay Office,Balintawak St.,Barangay 1,14.112387,121.555653,Dulo ng balintawak street,Open,8:00am - 5:00pm,NaN,Mark Gabriel E. Susin,2026-10-03,NaN,Yes,raw_dataset_5
336,LUC_B05_003,Pedron Dental Clinic,Health,Dental Clinic,NaN,Barangay 1,14.112435,121.555725,near brgy 5 multi-purpose hall,open,Monday-Saturday: 9:00 AM - 6 PM,FB: PedronDentalClinic,"Dela Cruz, Shane Theresse A.",2026-10-03,NaN,Yes,raw_dataset_5
337,LUC_B05_004,SK Hall,Government,Barangay Office,Balintawak St.,Barangay 1,14.112577,121.555748,near brgy. hall,close,NaN,NaN,"Liwanag, Micaela A.",2026-10-03,NaN,Yes,raw_dataset_5
338,LUC_B05_005,Mikay Sari-Sari Store,Food and Dining,Restaurant,Balintawak st.,Barangay 1,14.112661,121.555883,Near Lote fitness gym and Multi-purpose hall,open,7:00am to 8:00pm,NaN,Mark Gabriel E. Susim,2026-10-03,NaN,Yes,raw_dataset_5
357,LUC_B05_022,Nonette's Store,Retail,Sari Sari Store,E. Zurbano Street,Barangay 1,14.113122,121.553387,Palola Way,Open,NaN,NaN,Mark Gabriel E. Susim,2026-10-03,NaN,Yes,raw_dataset_5
362,LUC_B05_027,Pablo's Store,Retail,Sari Sari Store,NaN,Barangay 1,14.112965,121.554597,besides Pepet Restaurant,open,NaN,NaN,"Dela Cruz, Shane Theresse A.",2026-03-20,NaN,Yes,raw_dataset_5
366,LUC_B05_031,Che 2x,Food and Dining,Restaurant,Marcos Tigla street,Barangay 1,14.112910,121.554912,beside tapzi corner,Open,8:00am to 8:00pm,NaN,Mark Gabriel E. Susim,2026-10-03,NaN,Yes,raw_dataset_5
390,LUC_B04_020,Pearl Vigil Hall Memorial Homes,Other,Other,Gomburza,Barangay 1,14.115535,121.552808,NaN,Open,24hrs,NaN,"ERINCO, Raphael Joshua V.",2026-09-29,NaN,Yes,raw_dataset_6
425,LUC_B08_025,Gold Fortune General Merchandise,Retail,Other,A. Racelis,Barangay 1,14.113981,121.554588,NaN,Open,NaN,NaN,"ERINCO, Raphael Joshua V.",2026-10-01,NaN,Yes,raw_dataset_6
431,LUC_B08_041,Baliwag,Retail,Other,A. Racelis,Barangay 1,14.114216,121.554033,NaN,Open,7:00am - 12:00am,NaN,"ARELLANO, Arvin L.",2026-10-01,NaN,Yes,raw_dataset_6
432,LUC_B08_042,Monday's fruit and vegetables,Retail,Other,A. Racelis,Barangay 1,14.114289,121.553917,NaN,Open,7:30am - 8:00pm,NaN,"ERINCO, Raphael Joshua V.",2026-10-01,NaN,Yes,raw_dataset_6
561,LUC_B02_079,One Day Express Laundry Service,Personal Services,Laundry,A. Racelis,Barangay 1,14.112923,121.556970,NaN,Open,NaN,NaN,"RAMOS, Isaih Thomas, E.",2026-09-30,NaN,Yes,raw_dataset_7
565,LUC_B02_083,Ratio Agri Supply,Retail,Grocery,A. Racelis,Barangay 1,14.113067,121.556431,NaN,Open,NaN,NaN,"TERRENAL, Tiara Joy, V.",2026-09-30,Animal Feeds,Yes,raw_dataset_7

## Gerenal Data Cleaning and Handling Missing Values

The Structure Audit: See data types and missing value counts

df.info()

The Statistical Audit: See averages, min, max (spots wild outliers instantly)

df.describe()

The Emptiness Audit: Count exactly how many NaN values sit in each column

df.isnull().sum()

The Duplication Audit: Check if rows are accidentally duplicated

df.duplicated().sum()

In [91]:
# .between() can be used for datetime to check if the dates are within the certain range

In [92]:
missing = df.isnull().sum().to_frame('n_missing')
missing.sort_values('n_missing', ascending=False)

                      n_missing
remarks                     706
location_description        668
opening_hours               640
contact_info                625
name                         23
date_collected               14
street                        9
operating_status              5
collector                     2
feature_id                    0
Longitude                     0
barangay                      0
subcategory                   0
category                      0
Latitude                      0
verified                      0
source                        0

In [93]:
duplicate_ids = df[df['feature_id'].duplicated(keep=False)]

duplicate_ids = duplicate_ids.sort_values('feature_id')

duplicate_ids

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
540,LUC_B02_059,Kantuhan Food House,Food and Dining,Eatery,Don V. Cadelina,Barangay 2,14.113099,121.555172,NaN,Open,NaN,NaN,"HUTAMARES, Franchezka, M.",2026-09-30,NaN,Yes,raw_dataset_7
541,LUC_B02_059,Bahay Pamahalaan Barangay 2,Government,Barangay Office,Don V. Cadelina,Barangay 2,14.113136,121.555209,NaN,Open,NaN,NaN,"RAMOS, Isaih Thomas, E.",2026-09-30,NaN,Yes,raw_dataset_7
694,LUC_B03_025,Trendee by Dee Jay Abustan,Personal Services,Fashion Design,Armando Racelis Avenue,Barangay 3,14.115593,121.551067,NaN,Open,9:00 am - 5:00 pm,0917-549-7466,"ANGULO, Leira Rose A.",2026-03-10,NaN,Yes,raw_dataset_9
693,LUC_B03_025,Jepoy Sisig,Food and Dining,Eatery,Armando Racelis Avenue,Barangay 3,14.115499,121.551267,NaN,Open,3:00 pm - 10:00 pm,0962-133-6409,"MERCADO, Mhaylan Say R.",2026-03-10,NaN,Yes,raw_dataset_9
604,LUC_B04_001,ZUREA Hotel,Accommodation,Hotel,Conception Street,Barangay 4,14.116233,121.552481,NaN,OPEN,24 hours,0917854969 - Jeffrey Zurbano,"TERRENAL, TIARA",2026-10-01,NaN,Yes,raw_dataset_8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,LUC_B09_125,Lena's Store,Retail,Sari Sari Store,Gil Rada,Barangay 9,14.118387,121.557556,NaN,Open,NaN,NaN,"Reginal, Reynel M.",2026-10-03,NaN,Yes,raw_dataset_3
12,LUC_B10_012,Itlog ni KUYA,Food and Dining,Grocery,Quezon avenue,Barangay 10,14.112911,121.558054,NaN,open,NaN,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
11,LUC_B10_012,BugMac,Food and Dining,Fast Food,Quezon avenue,Barangay 10,14.112949,121.558052,NaN,open,24/7,NaN,"PALEGAR, LUIS ALPHONSO N.",2026-03-10,NaN,Yes,raw_dataset_1
31,LUC_B10_031,Boss Tabi Inihaw,Food and Dining,Eatery,Quezon Avenue,Barangay 10,14.113625,121.557573,NaN,open,NaN,09157217881,"VITAL, FARRELL RICHARD E.",2026-03-10,NaN,Yes,raw_dataset_1
30,LUC_B10_031,Boss Tabi Inihaw,Food and Dining,Eatery,Quezon Avenue,Barangay 10,14.113625,121.557573,NaN,open,NaN,09157217881,"VITAL, FARRELL RICHARD E.",2026-03-10,NaN,Yes,raw_dataset_1

In [94]:
duplicate_names = df[
    df['name'].notna() &
    df['name'].duplicated(keep=False)
].sort_values('name')

duplicate_names

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
270,LUC_B08_011,Abcede's Resto,Food and Dining,Restaurant,Quezon Avenue,Barangay 8,14.113632,121.556235,NaN,Open,NaN,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4
101,LUC_B10_102,Abcede's Resto,Food and Dining,Restaurant,Quezon Avenue,Barangay 10,14.113603,121.556273,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
144,LUC_B09_001,Agee's Food Hub,Food and Dining,Restaurant,La Purisima Conception,Barangay 9,14.114794,121.555984,First floor,Open,NaN,NaN,"Salumbides, Emanuel A.",2026-10-02,NaN,Yes,raw_dataset_3
113,LUC_B01_012,Agee's Food Hub,Food and Dining,Eatery,La Purisma Concepcion,Barangay 1,14.114733,121.555983,NaN,open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
30,LUC_B10_031,Boss Tabi Inihaw,Food and Dining,Eatery,Quezon Avenue,Barangay 10,14.113625,121.557573,NaN,open,NaN,09157217881,"VITAL, FARRELL RICHARD E.",2026-03-10,NaN,Yes,raw_dataset_1
31,LUC_B10_031,Boss Tabi Inihaw,Food and Dining,Eatery,Quezon Avenue,Barangay 10,14.113625,121.557573,NaN,open,NaN,09157217881,"VITAL, FARRELL RICHARD E.",2026-03-10,NaN,Yes,raw_dataset_1
419,LUC_B08_009,Cebuana Lhuillier,Financial,Pawnshop,A. Racelis,Barangay 8,14.113638,121.555432,NaN,Open,8:00am - 6:00pm,NaN,"ARELLANO, Arvin L.",2026-10-01,NaN,Yes,raw_dataset_6
172,LUC_B09_029,Cebuana Lhuillier,Financial,Remittance Center,Regidor,Barangay 9,14.115316,121.555777,NaN,Open,8:00 am - 9:00 pm,9283859030,"Salumbides, Emanuel A.",2026-10-02,NaN,Yes,raw_dataset_3
163,LUC_B09_020,Colar,Retail,Clothing,Lopez Jaena,Barangay 9,14.115422,121.555259,NaN,Open,NaN,NaN,Escobal Gwyneth A.,2026-10-02,NaN,Yes,raw_dataset_3
162,LUC_B09_019,Colar,Retail,Clothing,Lopez jaena,Barangay 9,14.115398,121.555247,NaN,Open,NaN,NaN,"Salumbides, Emanuel A.",2026-10-02,NaN,Yes,raw_dataset_3
149,LUC_B09_006,Colar,Retail,Sari Sari Store,Regidor,Barangay 9,14.115085,121.555625,NaN,Closed,NaN,NaN,"Reginal, Reynel M.",2026-10-02,NaN,Yes,raw_dataset_3
197,LUC_B09_054,Jepoy Sisig,Food and Dining,Fast Food,Lucban-Sampaloc Road,Barangay 9,14.116355,121.555640,NaN,Open,NaN,NaN,"Salumbides, Emanuel A.",2026-10-02,NaN,Yes,raw_dataset_3
693,LUC_B03_025,Jepoy Sisig,Food and Dining,Eatery,Armando Racelis Avenue,Barangay 3,14.115499,121.551267,NaN,Open,3:00 pm - 10:00 pm,0962-133-6409,"MERCADO, Mhaylan Say R.",2026-03-10,NaN,Yes,raw_dataset_9
52,LUC_B10_053,Lucky Bookstore,Retail,Other,Balintawak Street,Barangay 10,14.113441,121.556312,School and Office Supplies,open,NaN,NaN,"ABRACIA, JESHEILA ANGELA J.",2026-03-10,NaN,Yes,raw_dataset_1
51,LUC_B10_052,Lucky Bookstore,Retail,Other,Balintawak Street,Barangay 10,14.113405,121.556308,School and Office Supplies,open,NaN,NaN,"ABRACIA, JESHEILA ANGELA J.",2026-03-10,NaN,Yes,raw_dataset_1
411,LUC_B08_001,Lucky Bookstore,Retail,Other,Balintawak,Barangay 8,14.113425,121.556228,NaN,Open,NaN,NaN,"ARELLANO, Arvin L.",2026-10-01,NaN,Yes,raw_dataset_6
77,LUC_B10_078,Marella,Other,Other,Quezon Avenue,Barangay 10,14.113183,121.557200,tapat ng ongville,open,NaN,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
457,LUC_B08_087,Marella,Retail,Clothing,Quezon Avenue,Barangay 8,14.113870,121.555818,NaN,Open,NaN,NaN,"ERINCO, Raphael Joshua V.",2026-10-01,NaN,Yes,raw_dataset_6
368,LUC_B05_033,NFP Boarding House,Accommodation,Boarding House,Marcos Tigla Street,Barangay 5,14.112787,121.555098,near Campville's broad and tikoy shop,Open,7:00am to 9:00pm,0916 245 3954,Mark Gabriel E. Susin,2026-10-03,NaN,Yes,raw_dataset_5
340,LUC_BO5_006,NFP Boarding House,Other,Boarding House,Marcos Tigla St.,Barangay 5,14.112877,121.555138,near camp ville's,open,NaN,09162453954,"Liwanag, Micaela A.",2026-10-03,NaN,Yes,raw_dataset_5
88,LUC_B10_089,Palawan Pawnshop,Financial,Pawnshop,Quezon Avenue,Barangay 10,14.113430,121.556790,NaN,open,8:00 AM - 5:30 PM,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
285,LUC_B08_037,Palawan Pawnshop,Financial,Pawnshop,Quezon Avenue,Barangay 8,14.114408,121.554627,NaN,Closed,NaN,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4
66,LUC_B10_067,Pectos Bakery,Food and Dining,Bakery,Quezon Avenue,Barangay 10,14.112955,121.557638,NaN,open,NaN,NaN,"ABRACIA, JESHEILA ANGELA J.",2026-03-10,NaN,Yes,raw_dataset_1
286,LUC_B08_038,Pectos Bakery,Food and Dining,Bakery,Quezon Avenue,Barangay 8,14.114413,121.554493,NaN,Open,NaN,NaN,"De Chavez, Sharaine Princess P.",2026-10-01,NaN,Yes,raw_dataset_4
489,LUC_B08_149,Potato Corner,Food and Dining,Other,Rizal Avenue,Barangay 8,14.114422,121.554848,NaN,Open,NaN,NaN,"ARELLANO, Arvin L.",2026-10-01,NaN,Yes,raw_dataset_6
304,LUC_B08_075,Potato Corner,Food and Dining,Fast Food,San Luis,Barangay 8,14.114178,121.555778,NaN,Open,NaN,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4
482,LUC_B08_142,Raquel Pawnshop,Financial,Pawnshop,Rizal Avenue,Barangay 8,14.114923,121.555020,NaN,Open,NaN,NaN,"ERINCO, Raphael Joshua V.",2026-10-01,NaN,Yes,raw_dataset_6
90,LUC_B10_091,Raquel Pawnshop,Financial,Pawnshop,Quezon Avenue,Barangay 10,14.113382,121.556750,NaN,open,8:00 AM - 5:00 PM,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1
395,LUC_B04_025,SJ2 Sari-Sari Store,Retail,Sari Sari Store,Conception,Barangay 4,14.115889,121.553097,NaN,Open,NaN,NaN,"ERINCO, Raphael Joshua V.",2026-09-29,NaN,Yes,raw_dataset_6
605,LUC_B04_002,SJ2 Sari-Sari Store,Retail,Sari Sari Store,Gomburza Street,Barangay 4,14.115949,121.553096,NaN,CLOSED,NaN,NaN,"Gonzales, Louis",2026-10-01,NaN,Yes,raw_dataset_8
152,LUC_B09_009,Sabon Station,Retail,Other,La Purisima Conception,Barangay 9,14.114846,121.555751,NaN,Closed,NaN,NaN,Reginal Reynel M,2026-10-02,NaN,Yes,raw_dataset_3
238,LUC_B09_095,Sabon Station,Personal Services,Other,Regidor,Barangay 9,14.117803,121.557026,NaN,Open,NaN,NaN,"Salumbides, Emanuel A.",2026-10-03,Cleaning services,Yes,raw_dataset_3
44,LUC_B10_045,Shiela's Frozen Product,Retail,Sari Sari Store,San Luis,Barangay 10,14.113898,121.556455,Frozen products store and kiping store,open,NaN,NaN,"VITAL, RICHARD FARRELL E.",2026-03-10,NaN,Yes,raw_dataset_1
467,LUC_B08_107,Shiela's Frozen Product,Retail,Other,San Luis,Barangay 8,14.113922,121.556410,NaN,Open,NaN,NaN,"ERINCO, Raphael Joshua V.",2026-10-01,NaN,Yes,raw_dataset_6
119,LUC_B02_025,Ven's Puto Seko,Food and Dining,Souvenir,A. Bonifacio,Barangay 2,14.113378,121.555077,NaN,Closed,NaN,NaN,"ALFARO, Justin Alexandre, B",2026-09-29,NaN,Yes,raw_dataset_2
426,LUC_B08_026,Ven's Puto Seko,Retail,Bakery,A. Racelis,Barangay 8,14.114022,121.554459,NaN,Open,NaN,NaN,"APOSTOL, Janelle Mae A.",2026-10-01,NaN,Yes,raw_dataset_6
437,LUC_B08_047,Ven's Puto Seko,Retail,Bakery,Quezon Avenue,Barangay 8,14.114597,121.554215,NaN,Open,NaN,NaN,"ARELLANO, Arvin L.",2026-10-01,NaN,Yes,raw_dataset_6
50,LUC_B10_051,Viewers Digital Solution,Retail,Electronics,Balintawak Street,Barangay 10,14.113692,121.556385,Gadgets Shop,open,NaN,NaN,"ABRACIA, JESHEILA ANGELA J.",2026-03-10,NaN,Yes,raw_dataset_1
465,LUC_B08_105,Viewers Digital Solution,Retail,Electronics,Quezon Avenue,Barangay 8,14.113803,121.556266,NaN,Open,NaN,NaN,"APOSTOL, Janelle Mae A.",2026-10-01,NaN,Yes,raw_dataset_6
604,LUC_B04_001,ZUREA Hotel,Accommodation,Hotel,Conception Street,Barangay 4,14.116233,121.552481,NaN,OPEN,24 hours,0917854969 - Jeffrey Zurbano,"TERRENAL, TIARA",2026-10-01,NaN,Yes,raw_dataset_8
371,LUC_B04_001,ZUREA Hotel,Accommodation,Hotel,Conception,Barangay 4,14.116247,121.552579,NaN,Open,NaN,NaN,"ARELLANO, Arvin, L.",2026-09-29,NaN,Yes,raw_dataset_6

In [95]:
duplicate_coordinates = df[
    df[['Latitude', 'Longitude']].duplicated(keep=False)
].sort_values(['Latitude', 'Longitude'])

duplicate_coordinates

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
0,LUC_B10_001,"mommy's tacos, burgers and pizzas",Food and Dining,Eatery,G.Cadeliña,Barangay 10,14.112738,121.557460,food stall at the front with an eatery inside,open,9:00AM - 8:00pm,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
1,LUC_B10_002,bnb laundry,Personal Services,Laundry,G.Cadeliña,Barangay 10,14.112738,121.557460,"Next to mommy's tacos, burgers and pizzas",open,7:00AM - 7:00pm,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
61,LUC_B10_062,Kuya Richard,Retail,Sari Sari Store,Quezon Avenue,Barangay 10,14.112825,121.557915,NaN,open,NaN,09070708952,"ABRACIA, JESHEILA ANGELA J.",2026-03-10,NaN,Yes,raw_dataset_1
62,LUC_B10_063,Cozy Travelers,Professional Services,Lodge,Quezon Avenue,Barangay 10,14.112825,121.557915,NaN,open,NaN,09152524452,"ABRACIA, JESHEILA ANGELA J.",2026-03-10,NaN,Yes,raw_dataset_1
63,LUC_B10_064,Lap Sign Arts,Professional Services,Printing Shop,Quezon Avenue,Barangay 10,14.112825,121.557915,NaN,open,NaN,09289058908,"ABRACIA, JESHEILA ANGELA J.",2026-03-10,NaN,Yes,raw_dataset_1
76,LUC_B10_077,The Thrifters Ave Fashion Shop,Retail,Clothing,Quezon Avenue,Barangay 10,14.113183,121.557200,tapat ng ongville,open,NaN,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
77,LUC_B10_078,Marella,Other,Other,Quezon Avenue,Barangay 10,14.113183,121.557200,tapat ng ongville,open,NaN,NaN,"PANDAKILA, HEERO MILES R.",2026-03-10,NaN,Yes,raw_dataset_1
30,LUC_B10_031,Boss Tabi Inihaw,Food and Dining,Eatery,Quezon Avenue,Barangay 10,14.113625,121.557573,NaN,open,NaN,09157217881,"VITAL, FARRELL RICHARD E.",2026-03-10,NaN,Yes,raw_dataset_1
31,LUC_B10_031,Boss Tabi Inihaw,Food and Dining,Eatery,Quezon Avenue,Barangay 10,14.113625,121.557573,NaN,open,NaN,09157217881,"VITAL, FARRELL RICHARD E.",2026-03-10,NaN,Yes,raw_dataset_1
142,LUC_B02_048,GOGO SHAMAN LENDING CORPORATION,Financial,Remittance Center,A. Racelis,Barangay 2,14.114518,121.553248,Second Floor,Closed,9:00 AM - 3:00 PM,9182845879.0,"RAMOS, Isaih Thomas, E.",2026-09-29,NaN,Yes,raw_dataset_2
143,LUC_B02_049,KMB Dog & Cat Clinic,Health,Clinic,A. Racelis,Barangay 2,14.114518,121.553248,NaN,Closed,NaN,9999416182.0,"HUTAMARES, Franchezka, M.",2026-09-29,NaN,Yes,raw_dataset_2
699,LUC_B06_001,RMT's Clinical Laboratory,Health,Clinic,Placencia Street,Barangay 6,14.115498,121.554032,corner of the street. connected to RRN Interac...,open,NaN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10
700,LUC_B06_002,RRN Integrative Health Clinic,Health,Clinic,Placencia Street,Barangay 6,14.115498,121.554032,Corner of the street. Connected to RMT's Clini...,open,9:00AM-12:00NN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10
701,LUC_B06_003,The Skin Health Clinic,Health,Clinic,Placencia Street,Barangay 6,14.115498,121.554032,Corner of the street. Connected with RMT's Cli...,open,9:30AM-1:00PM,NaN,"Libao, Ried Carlo C.",2026-05-10,Dermatology Clinic,Yes,raw_dataset_10
702,LUC_B06_004,Parinas Medical Clinic,Health,Clinic,Placencia Street,Barangay 6,14.115498,121.554032,Corner of the street. Connected to RRN Integra...,open,NaN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10
705,LUC_B06_007,Rolan's Barbershop,Personal Services,Barbershop,La Purisima Concepcion,Barangay 6,14.115578,121.553918,NaN,open,NaN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10
706,LUC_B06_008,Jane Footwear,Retail,Clothing,La Purisima Concepcion,Barangay 6,14.115578,121.553918,NaN,open,NaN,NaN,"Libao, Ried Carlo C.",2026-05-10,NaN,Yes,raw_dataset_10
752,LUC_B06_054,Barangay 6 CDC,Other,CDC,Katipunan,Barangay 6,14.117035,121.553243,Next to Brgy Hall,open,NaN,NaN,"Inoc, Dyan Michelle N.",2026-05-10,NaN,Yes,raw_dataset_10
753,LUC_B06_055,Baby Empanada by Chef Noirs,Food and Dining,Eatery,Katipunan,Barangay 6,14.117035,121.553243,NaN,open,NaN,NaN,"Inoc, Dyan Michelle N.",2026-05-10,NaN,Yes,raw_dataset_10

In [96]:
print(df['Latitude'].min())
print(df['Latitude'].max())

print(df['Longitude'].min())
print(df['Longitude'].max())

14.11230458
14.11881973
121.550036408
121.558576667

In [97]:
bad_coordinates = df[
    (df['Latitude'] < 0) |
    (df['Latitude'] > 90) |
    (df['Longitude'] < -180) |
    (df['Longitude'] > 180)
]

bad_coordinates

Empty DataFrame
Columns: [feature_id, name, category, subcategory, street, barangay, Latitude, Longitude, location_description, operating_status, opening_hours, contact_info, collector, date_collected, remarks, verified, source]
Index: []

In [98]:
category_fixes = {
    'Professional Sevices': 'Professional Services'
}

df['category'] = df['category'].replace(category_fixes)
df['category']

0            Food and Dining
1          Personal Services
2                     Retail
3                      Other
4            Food and Dining
               ...
762                   Retail
763                    Other
764    Professional Services
765          Food and Dining
766                  Tourism
Name: category, Length: 767, dtype: str

In [99]:
status_fixes = {
    'open': 'Open',
    'OPEN': 'Open',
    'Oepn': 'Open',
    'close': 'Closed',
    'Close': 'Closed',
    'CLOSED': 'Closed',
    'closed': 'Closed',
    'closel': 'Closed'
}

df['operating_status'] = df['operating_status'].replace(status_fixes)
df['operating_status']

0      Open
1      Open
2      Open
3      Open
4      Open
       ...
762    Open
763    Open
764    Open
765    Open
766    Open
Name: operating_status, Length: 767, dtype: str

In [100]:
subcategory_fixes = {
    'Sari Sari Store': 'Sari-Sari Store',
    'Sari-sari Store': 'Sari-Sari Store'
}

df['subcategory'] = df['subcategory'].replace(subcategory_fixes)

In [101]:
feature_id_fixes = {
    'LUC_BO5_001': 'LUC_B05_001',
    'LUC-B08_036': 'LUC_B08_036',
    'LUC _B04_008': 'LUC_B04_008'
}

df['feature_id'] = df['feature_id'].replace(feature_id_fixes)

In [102]:
df['id_barangay'] = (
    df['feature_id']
    .str.extract(r'LUC_B(\d{2})_')[0]
)

In [103]:
df['id_barangay'] = pd.to_numeric(
    df['id_barangay'],
    errors='coerce'
)

In [104]:
df['actual_barangay'] = (
    df['barangay']
    .str.extract(r'(\d+)')[0]
)

df['actual_barangay'] = pd.to_numeric(
    df['actual_barangay'],
    errors='coerce'
)

In [105]:
id_barangay_mismatch = df[
    df['id_barangay'] != df['actual_barangay']
]

id_barangay_mismatch

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source,id_barangay,actual_barangay
102,LUC_B01_001,Mr. Yap Fresh Buko,Other,Other,Quezon Avenue,Barangay 10,14.113918,121.558059,NaN,Open,NaN,NaN,"Cadao, Janusz Gabriel S.",2026-03-10,NaN,Yes,raw_dataset_1,1.0,10
284,LUC_B08_036,SJS,Retail,Other,Quezon Avenue,Barangay 1,14.114383,121.554680,NaN,Open,NaN,NaN,"De Chavez, Sharaine Princess, P.",2026-10-01,NaN,Yes,raw_dataset_4,8.0,1
335,LUC_B05_002,Brgy. 5 Multi-Purpose Hall,Government,Barangay Office,Balintawak St.,Barangay 1,14.112387,121.555653,Dulo ng balintawak street,Open,8:00am - 5:00pm,NaN,Mark Gabriel E. Susin,2026-10-03,NaN,Yes,raw_dataset_5,5.0,1
336,LUC_B05_003,Pedron Dental Clinic,Health,Dental Clinic,NaN,Barangay 1,14.112435,121.555725,near brgy 5 multi-purpose hall,Open,Monday-Saturday: 9:00 AM - 6 PM,FB: PedronDentalClinic,"Dela Cruz, Shane Theresse A.",2026-10-03,NaN,Yes,raw_dataset_5,5.0,1
337,LUC_B05_004,SK Hall,Government,Barangay Office,Balintawak St.,Barangay 1,14.112577,121.555748,near brgy. hall,Closed,NaN,NaN,"Liwanag, Micaela A.",2026-10-03,NaN,Yes,raw_dataset_5,5.0,1
338,LUC_B05_005,Mikay Sari-Sari Store,Food and Dining,Restaurant,Balintawak st.,Barangay 1,14.112661,121.555883,Near Lote fitness gym and Multi-purpose hall,Open,7:00am to 8:00pm,NaN,Mark Gabriel E. Susim,2026-10-03,NaN,Yes,raw_dataset_5,5.0,1
340,LUC_BO5_006,NFP Boarding House,Other,Boarding House,Marcos Tigla St.,Barangay 5,14.112877,121.555138,near camp ville's,Open,NaN,09162453954,"Liwanag, Micaela A.",2026-10-03,NaN,Yes,raw_dataset_5,NaN,5
346,LUC_BO5_011,Abing Store,Retail,Sari-Sari Store,Fidel rada St,Barangay 5,14.113513,121.554040,near sldc grocery store,Open,NaN,NaN,"Liwanag, Micaela A.",2026-10-03,NaN,Yes,raw_dataset_5,NaN,5
349,LUC_BO5_014,La Bubble Laundry Shop,Personal Services,Laundry,Fidel rada St,Barangay 5,14.114045,121.552947,near palengke,Closed,NaN,09273757197,"Liwanag, Micaela A.",2026-10-03,NaN,Yes,raw_dataset_5,NaN,5
357,LUC_B05_022,Nonette's Store,Retail,Sari-Sari Store,E. Zurbano Street,Barangay 1,14.113122,121.553387,Palola Way,Open,NaN,NaN,Mark Gabriel E. Susim,2026-10-03,NaN,Yes,raw_dataset_5,5.0,1
362,LUC_B05_027,Pablo's Store,Retail,Sari-Sari Store,NaN,Barangay 1,14.112965,121.554597,besides Pepet Restaurant,Open,NaN,NaN,"Dela Cruz, Shane Theresse A.",2026-03-20,NaN,Yes,raw_dataset_5,5.0,1
366,LUC_B05_031,Che 2x,Food and Dining,Restaurant,Marcos Tigla street,Barangay 1,14.112910,121.554912,beside tapzi corner,Open,8:00am to 8:00pm,NaN,Mark Gabriel E. Susim,2026-10-03,NaN,Yes,raw_dataset_5,5.0,1
390,LUC_B04_020,Pearl Vigil Hall Memorial Homes,Other,Other,Gomburza,Barangay 1,14.115535,121.552808,NaN,Open,24hrs,NaN,"ERINCO, Raphael Joshua V.",2026-09-29,NaN,Yes,raw_dataset_6,4.0,1
425,LUC_B08_025,Gold Fortune General Merchandise,Retail,Other,A. Racelis,Barangay 1,14.113981,121.554588,NaN,Open,NaN,NaN,"ERINCO, Raphael Joshua V.",2026-10-01,NaN,Yes,raw_dataset_6,8.0,1
431,LUC_B08_041,Baliwag,Retail,Other,A. Racelis,Barangay 1,14.114216,121.554033,NaN,Open,7:00am - 12:00am,NaN,"ARELLANO, Arvin L.",2026-10-01,NaN,Yes,raw_dataset_6,8.0,1
432,LUC_B08_042,Monday's fruit and vegetables,Retail,Other,A. Racelis,Barangay 1,14.114289,121.553917,NaN,Open,7:30am - 8:00pm,NaN,"ERINCO, Raphael Joshua V.",2026-10-01,NaN,Yes,raw_dataset_6,8.0,1
561,LUC_B02_079,One Day Express Laundry Service,Personal Services,Laundry,A. Racelis,Barangay 1,14.112923,121.556970,NaN,Open,NaN,NaN,"RAMOS, Isaih Thomas, E.",2026-09-30,NaN,Yes,raw_dataset_7,2.0,1
565,LUC_B02_083,Ratio Agri Supply,Retail,Grocery,A. Racelis,Barangay 1,14.113067,121.556431,NaN,Open,NaN,NaN,"TERRENAL, Tiara Joy, V.",2026-09-30,Animal Feeds,Yes,raw_dataset_7,2.0,1
620,LIC_B04_014,FEBIS STORE,Retail,Grocery,Gomburza Street,Barangay 4,14.114897,121.552485,NaN,Closed,NaN,NaN,"HUTAMARES, CHEZKA",2026-10-01,NaN,Yes,raw_dataset_8,NaN,4
631,LUC_B04_023,SOUNDSTAGE,Personal Services,Other,Bonifacio Street,Barangay 5,14.114496,121.552555,NaN,Closed,NaN,NaN,"TERRENAL, TIARA",2026-10-01,NaN,Yes,raw_dataset_8,4.0,5
637,LUC_B04_026,PANSIT HABHABAN,Food and Dining,Eatery,Fidel Rada St.,Barangay 5,14.114336,121.552232,NaN,Closed,NaN,NaN,"GONZALES, LOUIS",2026-10-01,NaN,Yes,raw_dataset_8,4.0,5

In [106]:
df = df.drop(columns=['id_barangay', 'actual_barangay'])

## Manual Corrections and Value Fixing

In [107]:
missing = pd.DataFrame({
    'missing_count': df.isnull().sum(),
    'missing_percent': df.isnull().mean() * 100
})

missing = missing.sort_values(
    'missing_percent',
    ascending=False
)

missing

                      missing_count  missing_percent
remarks                         706        92.046936
location_description            668        87.092568
opening_hours                   640        83.441982
contact_info                    625        81.486310
name                             23         2.998696
date_collected                   14         1.825293
street                            9         1.173403
operating_status                  5         0.651890
collector                         2         0.260756
feature_id                        0         0.000000
Longitude                         0         0.000000
barangay                          0         0.000000
subcategory                       0         0.000000
category                          0         0.000000
Latitude                          0         0.000000
verified                          0         0.000000
source                            0         0.000000

In [108]:
df['date_collected'] = pd.to_datetime(
    df['date_collected'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [109]:
df['date_collected'].min()
df['date_collected'].max()

future_dates = df[
    df['date_collected'] > pd.Timestamp('2026-12-31')
]

future_dates

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
352,LUC_B05_017,Apo ni Luming pansitan,Food and Dining,Eatery,Marcus Tigla St,Barangay 5,14.113587,121.553157,front of orange house,Open,NaN,09685260922,"Liwanag, Micaela A.",2206-10-03,NaN,Yes,raw_dataset_5

In [110]:
df[df['date_collected'].isna()]

,feature_id,name,category,subcategory,street,barangay,Latitude,Longitude,location_description,operating_status,opening_hours,contact_info,collector,date_collected,remarks,verified,source
3,LUC_B10_004,ICE ICE BABY,Other,Other,G.Cadeliña,Barangay 10,14.112880,121.557524,front have a gate colored brown,Open,9:00AM-9:00PM,NaN,"BROQUEZA, MIKYLA C.",NaT,NaN,Yes,raw_dataset_1
4,LUC_B10_005,Zendong,Food and Dining,Eatery,G.Cadeliña,Barangay 10,14.112940,121.557613,grey metal gate,Open,NaN,NaN,"BROQUEZA, MIKYLA C.",NaT,NaN,Yes,raw_dataset_1
14,LUC_B10_015,Joey's Barber Shop,Personal Services,Barbershop,NaN,Barangay 10,14.112890,121.558177,NaN,Open,NaN,NaN,"BROQUEZA, MIKYLA C.",NaT,NaN,Yes,raw_dataset_1
15,LUC_B10_016,CELLPHONE REPAIR SHOP,Personal Services,Electronics,Quezon avenue,Barangay 10,14.112801,121.558230,NaN,Open,NaN,NaN,"BROQUEZA, MIKYLA C.",NaT,NaN,Yes,raw_dataset_1
16,LUC_B10_017,OHMPERE,Professional Services,Electronics,Quezon avenue,Barangay 10,14.112793,121.558313,NaN,Open,NaN,NaN,"BROQUEZA, MIKYLA C.",NaT,NaN,Yes,raw_dataset_1
17,LUC_B10_018,COFI MINDED CAMP,Food and Dining,Cafe,Quezon avenue,Barangay 10,14.112836,121.558182,NaN,Open,NaN,NaN,"BROQUEZA, MIKYLA C.",NaT,NaN,Yes,raw_dataset_1
18,LUC_B10_019,BRGY. MULTI PURPOSE HALL,Government,Barangay Office,San Luis,Barangay 10,14.112930,121.558487,NaN,Open,NaN,NaN,"VITAL, FARRELL RICHARD E.",NaT,NaN,Yes,raw_dataset_1
19,LUC_B10_020,Mamet's sari sari store,Retail,Sari-Sari Store,San Luis,Barangay 10,14.112900,121.558577,NaN,Open,NaN,NaN,"VITAL, FARRELL RICHARD E.",NaT,NaN,Yes,raw_dataset_1
20,LUC_B10_021,Oblenida's sari sari store,Retail,Sari-Sari Store,San Luis,Barangay 10,14.112935,121.558562,NaN,Open,NaN,NaN,"PALEGAR, LUIS ALPHONSO N.",NaT,NaN,Yes,raw_dataset_1
150,LUC_B09_007,Card Inc. Lucban Unit,Financial,Remittance Center,Regidor,Barangay 9,14.115047,121.555678,NaN,Open,NaN,NaN,"Salumbides, Emanuel A.",NaT,NaN,Yes,raw_dataset_3
178,LUC_B09_035,Kapedillera,Food and Dining,Cafe,Plaridel,Barangay 9,14.115621,121.555374,NaN,Open,NaN,NaN,"Reginal, Reynel M.",NaT,NaN,Yes,raw_dataset_3
422,LUC_B08_022,Arlene's Hall,Other,Other,A. Racelis,Barangay 8,14.113658,121.555232,NaN,Open,NaN,NaN,"ARELLANO, Arvin L.",NaT,Event Hall,Yes,raw_dataset_6
513,LUC_B02_001,NaN,Accommodation,Boarding House,A. Racelis,Barangay 2,14.112478,121.557781,NaN,NaN,NaN,NaN,NaN,NaT,NaN,Yes,raw_dataset_7
636,LUC_B04_025,"BARAY'S LECHON PARES, MAMI AT SILOG",Food and Dining,Eatery,Fidel Rada St.,Barangay 4,14.114325,121.552315,NaN,NaN,NaN,NaN,"HUTAMARES, CHEZKA",NaT,NaN,Yes,raw_dataset_8